export const ErrorCodes = {
  // Auth
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  // Game
  ROUND_NOT_WAITING: 'ROUND_NOT_WAITING',
  ROUND_NOT_FLYING: 'ROUND_NOT_FLYING',
  BET_ALREADY_PLACED: 'BET_ALREADY_PLACED',
  BET_NOT_FOUND: 'BET_NOT_FOUND',
  BET_ALREADY_CASHED: 'BET_ALREADY_CASHED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  BET_TOO_SMALL: 'BET_TOO_SMALL',
  BET_TOO_LARGE: 'BET_TOO_LARGE',
  GAME_STOPPED: 'GAME_STOPPED',
  // Wallet
  AMOUNT_TOO_SMALL: 'AMOUNT_TOO_SMALL',
  NO_CARD_AVAILABLE: 'NO_CARD_AVAILABLE',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  ALREADY_PROCESSED: 'ALREADY_PROCESSED',
  // Promo
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_MAX_USAGE: 'PROMO_MAX_USAGE',
  PROMO_INACTIVE: 'PROMO_INACTIVE',
  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT: 'RATE_LIMIT',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    public status: number = 400,
    message?: string
  ) {
    super(message || code);
    this.name = 'AppError';
  }
}
